Added CONTRIBUTING.md
ashutoshgithubs/iemhacks_DEV-G pull request #60
Opened 2024-05-12 20:09 UTC by suhanipaliwal

This PR fixes #50

2024-05-12 21:06 UTC, ashutoshgithubs requested changes
Hi @suhanipaliwal The PR looks good to me, please incorporate the requested grammatical corrections indicated in the snapshot and it should be good to be merged :)

<img width="410" alt="image" src="https://github.com/ashutoshgithubs/iemhacks_DEV-G/assets/97340498/cb334a28-8e71-40e7-8745-1488b6268183">

> After `admin` put full stop (.), v of `visit `and y of `you `should be capital. I think this file should be fit and grammatically correct as its like a booklet for contributors.

2024-05-13 18:38 UTC, suhanipaliwal commented
I have done the suggested corrections. Please check and merge the PR accordingly.

2024-05-14 12:04 UTC, ashutoshgithubs approved these changes

2024-05-14 12:06 UTC, merged

2024-05-14 12:19 UTC, ashutoshgithubs commented
@suhanipaliwal Thanks for your contribution! Your PR has been merged successfully. Keep contributing. Happy Coding :)